name: WebHookAPI-Push

on:
  push:
    branches:
      - main
    paths:
      - '.github/WebHookAPI-Push.yml'
      - 'litmus-preview-webhook/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Docker login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
      - name: Build and Push the Docker Image
        run: |
          cd litmus-preview-webhook
          docker build . -t ${{github.repository_owner}}/webhookapi:${{ steps.vars.outputs.branch }}-${{ steps.vars.outputs.sha_short }} -f build/Dockerfile --build-arg SLACK_WEBHOOK_LINK="${{ secrets.SLACK_WEBHOOK_LINK }}"
          docker push ${{github.repository_owner}}/webhookapi:${{ steps.vars.outputs.branch }}-${{ steps.vars.outputs.sha_short }}