name: WebHookAPI-Build

on:
  pull_request:
    branches:
      - main
    types: [ opened, synchronize, reopened ]
    paths:
      - '.github/workflows/WebHookAPI-Build.yml'
      - 'litmus-preview-webhook/**'

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "::set output name=img_tag::$(echo 'ci')"
      - name: Build the Docker Image
        run: |
          cd litmus-preview-webhook
          docker build . -t webhookapi:${{ steps.vars.outputs.img_tag }} -f build/Dockerfile --build-arg SLACK_WEBHOOK_LINK="${{ secrets.SLACK_WEBHOOK_LINK }}"